# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# [START build-credit-card-payments-app.app-configuration]
name = "<App Name>"
client_id = "<API Client ID>"
# [END build-credit-card-payments-app.app-configuration]
application_url = "https://example.com"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
